# Generated by Django 3.2.18 on 2023-04-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, verbose_name='投票項目名稱')),
                ('mdt', models.DateTimeField(auto_now=True, verbose_name='編輯時間')),
            ],
            options={
                'verbose_name': '投票項目',
                'verbose_name_plural': '投票項目',
                'ordering': ('-mdt',),
            },
        ),
        migrations.CreateModel(
            name='PollRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(blank=True, max_length=50, verbose_name='投票者')),
                ('mdt', models.DateTimeField(auto_now=True, verbose_name='編輯時間')),
                ('representor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteitems', to='mainapi.voteitems')),
            ],
            options={
                'verbose_name': '投票紀錄',
                'verbose_name_plural': '投票紀錄',
                'ordering': ('-mdt',),
            },
        ),
    ]
