# Generated by Django 3.2.18 on 2023-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='投票項目名稱')),
            ],
        ),
        migrations.DeleteModel(
            name='PollRecords',
        ),
        migrations.DeleteModel(
            name='VoteItems',
        ),
    ]
