# Generated by Django 3.2.18 on 2023-04-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0005_alter_vote_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_name',
            field=models.CharField(max_length=50, verbose_name='投票人暱稱'),
        ),
    ]
